export const EVENTS = {
  ROOM_CREATED: 'core:room-created',
  ROOM_CLOSED: 'core:room-closed',
  PLAYER_JOINED: 'core:player-joined',
  PLAYER_LEFT: 'core:player-left',
  PLAYER_KICKED: 'core:player-kicked',
  GAME_START: 'core:game-start',
  GAME_STOP: 'core:game-stop',
  GAME_ACTION: 'core:game-action',
  ROOM_UPDATED: 'room:updated',
  ROOM_CLOSED_NOTIFY: 'room:closed',
  CHAT_NEW: 'chat:new-message',
  PLAYER_KICKED_NOTIFY: 'player:kicked',
  GAME_STARTED: 'game:started',
  GAME_STOPPED: 'game:stopped',
  GAME_STATE: 'game:state',
};